#git tag -a v1.4.2 -m "SimplePOS v1.4.2"

name: create-release

on:
  push:
    tags:
      - "v*"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  OutputDirectory: ${{github.workspace}}/buildoutput

defaults:
  run:
    shell: pwsh
    

jobs:  
  build:    
    runs-on: windows-latest  

    steps:      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Get all history to allow automatic versioning using MinVer

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
     
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build -c release
        
      - name: Publish
        run: dotnet publish SimplePOS\SimplePOS.csproj -c release -r win-x86 -f net6.0-windows -p:PublishSingleFile=true --self-contained true -o ${{ env.OutputDirectory }}
        
      - uses: vimtor/action-zip@v1
        with:
          files: ${{ env.OutputDirectory }}
          dest: ${{ env.OutputDirectory }}/SimplePOS-${{  github.ref_name }}.zip
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ${{ env.OutputDirectory }}/SimplePOS-${{  github.ref_name }}.zip
          
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '${{ env.OutputDirectory }}/SimplePOS-${{  github.ref_name }}.zip'
          generateReleaseNotes: true
          prerelease: true